import { Muscles } from '../../../shared/Shared.model';

export const MUSCLES_OPTIONS: Muscles[] = [
    Muscles.Neck,
    Muscles.Feet,
    Muscles.UpperTrapezius,
    Muscles.Gastrocnemius,
    Muscles.Soleus,
    Muscles.LateralDeltoid,
    Muscles.InnerThigh,
    Muscles.WristExtensors,
    Muscles.WristFlexors,
    Muscles.Hands,
    Muscles.Groin,
    Muscles.Tibialis,
    Muscles.OuterQuadricep,
    Muscles.RectusFemoris,
    Muscles.InnerQuadricep,
    Muscles.LongHeadBicep,
    Muscles.ShortHeadBicep,
    Muscles.Obliques,
    Muscles.LowerAbdominals,
    Muscles.UpperAbdominals,
    Muscles.MidLowerPectoralis,
    Muscles.UpperPectoralis,
    Muscles.AnteriorDeltoid,
    Muscles.MedialHamstrings,
    Muscles.LateralHamstrings,
    Muscles.GluteusMaximus,
    Muscles.GluteusMedius,
    Muscles.LowerBack,
    Muscles.Lats,
    Muscles.MedialHeadTriceps,
    Muscles.LongHeadTriceps,
    Muscles.LateralHeadTriceps,
    Muscles.PosteriorDeltoid,
    Muscles.LowerTrapezius,
    Muscles.TrapsMiddle,
];

